# Generated by Django 5.1.3 on 2024-12-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EEGSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alpha_power', models.FloatField()),
                ('mean', models.FloatField()),
                ('max_value', models.FloatField()),
                ('standard_deviation', models.FloatField()),
                ('rms', models.FloatField()),
                ('kurtosis', models.FloatField()),
                ('skewness', models.FloatField()),
            ],
        ),
    ]
