# Generated by Django 5.1.3 on 2024-12-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eegsignal',
            name='alpha_power',
            field=models.FloatField(db_column='alpha_power'),
        ),
        migrations.RenameField(
            model_name='eegsignal',
            old_name='alpha_power',
            new_name='Alpha_Power',
        ),
        migrations.AlterField(
            model_name='eegsignal',
            name='kurtosis',
            field=models.FloatField(db_column='kurtosis'),
        ),
        migrations.RenameField(
            model_name='eegsignal',
            old_name='kurtosis',
            new_name='Kurtosis',
        ),
        migrations.AlterField(
            model_name='eegsignal',
            name='max_value',
            field=models.FloatField(db_column='max_value'),
        ),
        migrations.RenameField(
            model_name='eegsignal',
            old_name='max_value',
            new_name='Max',
        ),
        migrations.AlterField(
            model_name='eegsignal',
            name='mean',
            field=models.FloatField(db_column='mean'),
        ),
        migrations.RenameField(
            model_name='eegsignal',
            old_name='mean',
            new_name='Mean',
        ),
        migrations.AlterField(
            model_name='eegsignal',
            name='rms',
            field=models.FloatField(db_column='rms'),
        ),
        migrations.RenameField(
            model_name='eegsignal',
            old_name='rms',
            new_name='RMS',
        ),
        migrations.AlterField(
            model_name='eegsignal',
            name='skewness',
            field=models.FloatField(db_column='skewness'),
        ),
        migrations.RenameField(
            model_name='eegsignal',
            old_name='skewness',
            new_name='Skewness',
        ),
        migrations.AlterField(
            model_name='eegsignal',
            name='standard_deviation',
            field=models.FloatField(db_column='standard_deviation'),
        ),
        migrations.RenameField(
            model_name='eegsignal',
            old_name='standard_deviation',
            new_name='Standard_Deviation',
        ),
        migrations.AlterField(
            model_name='eegsignal',
            name='timestamp',
            field=models.DateTimeField(db_column='timestamp'),
        ),
    ]
