# Generated by Django 5.1.3 on 2024-12-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0002_alter_eegsignal_alpha_power_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eegsignal',
            name='Peak_to_Peak',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
