# Generated by Django 5.1.3 on 2024-12-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0003_eegsignal_peak_to_peak'),
    ]

    operations = [
        migrations.AddField(
            model_name='eegsignal',
            name='Abs_Diff_Signal',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
