# Generated by Django 5.1.3 on 2024-12-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0004_eegsignal_abs_diff_signal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eegsignal',
            name='Kurtosis',
            field=models.FloatField(blank=True, db_column='kurtosis', null=True),
        ),
        migrations.AlterField(
            model_name='eegsignal',
            name='Skewness',
            field=models.FloatField(blank=True, db_column='skewness', null=True),
        ),
    ]
